import pymongo, os
client = pymongo.MongoClient('127.0.0.1', 27017)
userdb = client['user']
maindb = client['main']
c18db = client['c18']
# c18db.drop_collection('roster')
# c18db.create_collection('roster')
# c18db.roster.insert_many([
'''
{'name':'万成伟'  , 'num':1 , 'gender':'男', 'posi-cadres':['体育委员'], 'num':1 ,'posi-repr':[]},
{'name':'万哲诚'  , 'num':2 , 'gender':'男', 'posi-cadres':[''], 'num':1 ,'posi-repr':[]},
{'name':'王子怡'  , 'num':3 , 'gender':'女', 'posi-cadres':[''], 'num':1 ,'posi-repr':[]},
{'name':'王子骏'  , 'num':4 , 'gender':'男', 'posi-cadres':[''], 'num':1 ,'posi-repr':['E', 'num':1 ,'C']},
{'name':'王亚卓'  , 'num':5 , 'gender':'男', 'posi-cadres':[''], 'num':1 ,'posi-repr':[]},
{'name':'王曦佳'  , 'num':6 , 'gender':'女', 'posi-cadres':['卫生委员'], 'num':1 ,'posi-repr':['E', 'num':1 ,'C']},
{'name':'邓剑锋'  , 'num':7 , 'gender':'男', 'posi-cadres':[''], 'num':1 ,'posi-repr':['P']},
{'name':'刘的菲'  , 'num':8 , 'gender':'女', 'posi-cadres':[''], 'num':1 ,'posi-repr':[]},
{'name':'刘泽霖'  , 'num':9 , 'gender':'男', 'posi-cadres':[''], 'num':1 ,'posi-repr':['CH']},
{'name':'刘诗语'  , 'num':10, 'gender':'女', 'posi-cadres':['']},
{'name':'汤沐乐'  , 'num':11, 'gender':'女', 'posi-cadres':[''], 'num':1 ,'posi-repr':['E']},
{'name':'孙一鸣'  , 'num':12, 'gender':'男', 'posi-cadres':[''], 'num':1 ,'posi-repr':[]},
{'name':'李双怡'  , 'num':13, 'gender':'女', 'posi-cadres':[''], 'num':1 ,'posi-repr':[]},
{'name':'李君傲'  , 'num':14, 'gender':'男', 'posi-cadres':[''], 'num':1 ,'posi-repr':['M']},
{'name':'李海容'  , 'num':15, 'gender':'女', 'posi-cadres':['班长', 'num':1 ,'团支书'], 'num':1 ,'posi-repr':['PH']},
{'name':'李璐'    , 'num':16, 'gender':'女', 'posi-cadres':[''], 'num':1 ,'posi-repr':['CH']},
{'name':'杨嘉勇'  , 'num':17, 'gender':'男', 'posi-cadres':['纪律委员'], 'num':1 ,'posi-repr':['G']},
{'name':'肖文艳'  , 'num':19, 'gender':'女', 'posi-cadres':[''], 'num':1 ,'posi-repr':[]},
{'name':'肖淳文'  , 'num':20, 'gender':'男', 'posi-cadres':['电教委员'], 'num':1 ,'posi-repr':['E', 'num':1 ,'CO']},
{'name':'汪佳仪'  , 'num':21, 'gender':'女', 'posi-cadres':['学习委员'], 'num':1 ,'posi-repr':['B']},
{'name':'陈凯'    , 'num':22, 'gender':'男', 'posi-cadres':['团支书'], 'num':1 ,'posi-repr':['PH']},
{'name':'罗麟书'  , 'num':23, 'gender':'女', 'posi-cadres':['宣传委员'], 'num':1 ,'posi-repr':['CH']},
{'name':'周子涵'  , 'num':24, 'gender':'男', 'posi-cadres':['班长'], 'num':1 ,'posi-repr':['M']},
{'name':'周沅'    , 'num':25, 'gender':'女', 'posi-cadres':['文艺委员'], 'num':1 ,'posi-repr':[]},
{'name':'周明宇'  , 'num':26, 'gender':'男', 'posi-cadres':['卫生委员'], 'num':1 ,'posi-repr':[]},
{'name':'赵闽润'  , 'num':27, 'gender':'男', 'posi-cadres':[''], 'num':1 ,'posi-repr':['CH']},
{'name':'姜静仪'  , 'num':28, 'gender':'女', 'posi-cadres':[''], 'num':1 ,'posi-repr':[]},
{'name':'袁景哲'  , 'num':30, 'gender':'男', 'posi-cadres':[''], 'num':1 ,'posi-repr':[]},
{'name':'夏伟'    , 'num':31, 'gender':'男', 'posi-cadres':[''], 'num':1 ,'posi-repr':[]},
{'name':'徐成'    , 'num':32, 'gender':'男', 'posi-cadres':[''], 'num':1 ,'posi-repr':[]},
{'name':'殷琪雅'  , 'num':33, 'gender':'女', 'posi-cadres':[''], 'num':1 ,'posi-repr':[]},
{'name':'郭筱星'  , 'num':34, 'gender':'女', 'posi-cadres':[''], 'num':1 ,'posi-repr':['H']},
{'name':'曹雨鑫'  , 'num':35, 'gender':'女', 'posi-cadres':[''], 'num':1 ,'posi-repr':['G']},
{'name':'章锦沛'  , 'num':36, 'gender':'女', 'posi-cadres':[''], 'num':1 ,'posi-repr':['E']},
{'name':'梁宸浩'  , 'num':37, 'gender':'男', 'posi-cadres':['卫生委员'], 'num':1 ,'posi-repr':[]},
{'name':'彭家岩'  , 'num':38, 'gender':'男', 'posi-cadres':[''], 'num':1 ,'posi-repr':['B']},
{'name':'彭程'    , 'num':39, 'gender':'男', 'posi-cadres':[''], 'num':1 ,'posi-repr':['CH']},
{'name':'喻飞扬'  , 'num':40, 'gender':'男', 'posi-cadres':[''], 'num':1 ,'posi-repr':[]},
{'name':'曾翔宇'  , 'num':41, 'gender':'男', 'posi-cadres':[''], 'num':1 ,'posi-repr':['H']},
{'name':'谢金'    , 'num':42, 'gender':'女', 'posi-cadres':['组织委员'], 'num':1 ,'posi-repr':[]},
{'name':'靳照弘'  , 'num':43, 'gender':'男', 'posi-cadres':[''], 'num':1 ,'posi-repr':[]},
{'name':'廖一馨'  , 'num':44, 'gender':'女', 'posi-cadres':['体育委员'], 'num':1 ,'posi-repr':['A']},
{'name':'熊芷仪'  , 'num':45, 'gender':'女', 'posi-cadres':[''], 'num':1 ,'posi-repr':[]},
{'name':'潘琛'    , 'num':46, 'gender':'男', 'posi-cadres':[''], 'num':1 ,'posi-repr':[]},
{'name':'戴善美'  , 'num':47, 'gender':'女', 'posi-cadres':[''], 'num':1 ,'posi-repr':[]},
{'name':'周一舟'  , 'num':48, 'gender':'男', 'posi-cadres':[''], 'num':1 ,'posi-repr':[]},
{'name':'兰周'    , 'num':49, 'gender':'男', 'posi-cadres':[''], 'num':1 ,'posi-repr':[]},
{'name':'欧阳胤阁', 'num':50, 'gender':'男', 'posi-cadres':[''], 'num':1 ,'posi-repr':[]}
'''
datas = [
{'name':'万成伟'  , 'num':1 ,'photo':'/c18/api/pictures/photos/01.jpg','gp':['/c18/api/pictures/gps/01/1.jpg','/c18/api/pictures/gps/01/2.jpg']},
{'name':'万哲诚'  , 'num':2 ,'photo':'/c18/api/pictures/photos/02.jpg','gp':['/c18/api/pictures/gps/02/1.jpg','/c18/api/pictures/gps/02/2.jpg']},
{'name':'王子怡'  , 'num':3 ,'photo':'/c18/api/pictures/photos/03.jpg','gp':['/c18/api/pictures/gps/03/1.jpg','/c18/api/pictures/gps/03/2.jpg']},
{'name':'王子骏'  , 'num':4 ,'photo':'/c18/api/pictures/photos/04.jpg','gp':['/c18/api/pictures/gps/04/1.jpg','/c18/api/pictures/gps/04/2.jpg']},
{'name':'王亚卓'  , 'num':5 ,'photo':'/c18/api/pictures/photos/05.jpg','gp':['/c18/api/pictures/gps/05/1.jpg','/c18/api/pictures/gps/05/2.jpg']},
{'name':'王曦佳'  , 'num':6 ,'photo':'/c18/api/pictures/photos/06.jpg','gp':['/c18/api/pictures/gps/06/1.jpg','/c18/api/pictures/gps/06/2.jpg']},
{'name':'邓剑锋'  , 'num':7 ,'photo':'/c18/api/pictures/photos/07.jpg','gp':['/c18/api/pictures/gps/07/1.jpg','/c18/api/pictures/gps/07/2.jpg']},
{'name':'刘的菲'  , 'num':8 ,'photo':'/c18/api/pictures/photos/08.jpg','gp':['/c18/api/pictures/gps/08/1.jpg','/c18/api/pictures/gps/08/2.jpg']},
{'name':'刘泽霖'  , 'num':9 ,'photo':'/c18/api/pictures/photos/09.jpg','gp':['/c18/api/pictures/gps/09/1.jpg','/c18/api/pictures/gps/09/2.jpg']},
{'name':'刘诗语'  , 'num':10,'photo':'/c18/api/pictures/photos/10.jpg','gp':['/c18/api/pictures/gps/10/1.jpg','/c18/api/pictures/gps/10/2.jpg']},
{'name':'汤沐乐'  , 'num':11,'photo':'/c18/api/pictures/photos/11.jpg','gp':['/c18/api/pictures/gps/11/1.jpg','/c18/api/pictures/gps/11/2.jpg']},
{'name':'孙一鸣'  , 'num':12,'photo':'/c18/api/pictures/photos/12.jpg','gp':['/c18/api/pictures/gps/12/1.jpg','/c18/api/pictures/gps/12/2.jpg']},
{'name':'李双怡'  , 'num':13,'photo':'/c18/api/pictures/photos/13.jpg','gp':['/c18/api/pictures/gps/13/1.jpg','/c18/api/pictures/gps/13/2.jpg']},
{'name':'李君傲'  , 'num':14,'photo':'/c18/api/pictures/photos/14.jpg','gp':['/c18/api/pictures/gps/14/1.jpg','/c18/api/pictures/gps/14/2.jpg']},
{'name':'李海容'  , 'num':15,'photo':'/c18/api/pictures/photos/15.jpg','gp':['/c18/api/pictures/gps/15/1.jpg','/c18/api/pictures/gps/15/2.jpg']},
{'name':'李璐'    , 'num':16,'photo':'/c18/api/pictures/photos/16.jpg','gp':['/c18/api/pictures/gps/16/1.jpg','/c18/api/pictures/gps/16/2.jpg']},
{'name':'杨嘉勇'  , 'num':17,'photo':'/c18/api/pictures/photos/17.jpg','gp':['/c18/api/pictures/gps/17/1.jpg','/c18/api/pictures/gps/17/2.jpg']},
{'name':'肖文艳'  , 'num':19,'photo':'/c18/api/pictures/photos/19.jpg','gp':['/c18/api/pictures/gps/19/1.jpg','/c18/api/pictures/gps/19/2.jpg']},
{'name':'肖淳文'  , 'num':20,'photo':'/c18/api/pictures/photos/20.jpg','gp':['/c18/api/pictures/gps/20/1.jpg','/c18/api/pictures/gps/20/2.jpg']},
{'name':'汪佳仪'  , 'num':21,'photo':'/c18/api/pictures/photos/21.jpg','gp':['/c18/api/pictures/gps/21/1.jpg','/c18/api/pictures/gps/21/2.jpg']},
{'name':'陈凯'    , 'num':22,'photo':'/c18/api/pictures/photos/22.jpg','gp':['/c18/api/pictures/gps/22/1.jpg','/c18/api/pictures/gps/22/2.jpg']},
{'name':'罗麟书'  , 'num':23,'photo':'/c18/api/pictures/photos/23.jpg','gp':['/c18/api/pictures/gps/23/1.jpg','/c18/api/pictures/gps/23/2.jpg']},
{'name':'周子涵'  , 'num':24,'photo':'/c18/api/pictures/photos/24.jpg','gp':['/c18/api/pictures/gps/24/1.jpg','/c18/api/pictures/gps/24/2.jpg']},
{'name':'周沅'    , 'num':25,'photo':'/c18/api/pictures/photos/25.jpg','gp':['/c18/api/pictures/gps/25/1.jpg','/c18/api/pictures/gps/25/2.jpg']},
{'name':'周明宇'  , 'num':26,'photo':'/c18/api/pictures/photos/26.jpg','gp':['/c18/api/pictures/gps/26/1.jpg','/c18/api/pictures/gps/26/2.jpg']},
{'name':'赵闽润'  , 'num':27,'photo':'/c18/api/pictures/photos/27.jpg','gp':['/c18/api/pictures/gps/27/1.jpg','/c18/api/pictures/gps/27/2.jpg']},
{'name':'姜静仪'  , 'num':28,'photo':'/c18/api/pictures/photos/28.jpg','gp':['/c18/api/pictures/gps/28/1.jpg','/c18/api/pictures/gps/28/2.jpg']},
{'name':'袁景哲'  , 'num':30,'photo':'/c18/api/pictures/photos/30.jpg','gp':['/c18/api/pictures/gps/30/1.jpg','/c18/api/pictures/gps/30/2.jpg']},
{'name':'夏伟'    , 'num':31,'photo':'/c18/api/pictures/photos/31.jpg','gp':['/c18/api/pictures/gps/31/1.jpg','/c18/api/pictures/gps/31/2.jpg']},
{'name':'徐成'    , 'num':32,'photo':'/c18/api/pictures/photos/32.jpg','gp':['/c18/api/pictures/gps/32/1.jpg','/c18/api/pictures/gps/32/2.jpg']},
{'name':'殷琪雅'  , 'num':33,'photo':'/c18/api/pictures/photos/33.jpg','gp':['/c18/api/pictures/gps/33/1.jpg','/c18/api/pictures/gps/33/2.jpg']},
{'name':'郭筱星'  , 'num':34,'photo':'/c18/api/pictures/photos/34.jpg','gp':['/c18/api/pictures/gps/34/1.jpg','/c18/api/pictures/gps/34/2.jpg']},
{'name':'曹雨鑫'  , 'num':35,'photo':'/c18/api/pictures/photos/35.jpg','gp':['/c18/api/pictures/gps/35/1.jpg','/c18/api/pictures/gps/35/2.jpg']},
{'name':'章锦沛'  , 'num':36,'photo':'/c18/api/pictures/photos/36.jpg','gp':['/c18/api/pictures/gps/36/1.jpg','/c18/api/pictures/gps/36/2.jpg']},
{'name':'梁宸浩'  , 'num':37,'photo':'/c18/api/pictures/photos/37.jpg','gp':['/c18/api/pictures/gps/37/1.jpg','/c18/api/pictures/gps/37/2.jpg']},
{'name':'彭家岩'  , 'num':38,'photo':'/c18/api/pictures/photos/38.jpg','gp':['/c18/api/pictures/gps/38/1.jpg','/c18/api/pictures/gps/38/2.jpg']},
{'name':'彭程'    , 'num':39,'photo':'/c18/api/pictures/photos/39.jpg','gp':['/c18/api/pictures/gps/39/1.jpg','/c18/api/pictures/gps/39/2.jpg']},
{'name':'喻飞扬'  , 'num':40,'photo':'/c18/api/pictures/photos/40.jpg','gp':['/c18/api/pictures/gps/40/1.jpg','/c18/api/pictures/gps/40/2.jpg']},
{'name':'曾翔宇'  , 'num':41,'photo':'/c18/api/pictures/photos/41.jpg','gp':['/c18/api/pictures/gps/41/1.jpg','/c18/api/pictures/gps/41/2.jpg']},
{'name':'谢金'    , 'num':42,'photo':'/c18/api/pictures/photos/42.jpg','gp':['/c18/api/pictures/gps/42/1.jpg','/c18/api/pictures/gps/42/2.jpg']},
{'name':'靳照弘'  , 'num':43,'photo':'/c18/api/pictures/photos/43.jpg','gp':['/c18/api/pictures/gps/43/1.jpg','/c18/api/pictures/gps/43/2.jpg']},
{'name':'廖一馨'  , 'num':44,'photo':'/c18/api/pictures/photos/44.jpg','gp':['/c18/api/pictures/gps/44/1.jpg','/c18/api/pictures/gps/44/2.jpg']},
{'name':'熊芷仪'  , 'num':45,'photo':'/c18/api/pictures/photos/45.jpg','gp':['/c18/api/pictures/gps/45/1.jpg','/c18/api/pictures/gps/45/2.jpg']},
{'name':'潘琛'    , 'num':46,'photo':'/c18/api/pictures/photos/46.jpg','gp':['/c18/api/pictures/gps/46/1.jpg','/c18/api/pictures/gps/46/2.jpg']},
{'name':'戴善美'  , 'num':47,'photo':'/c18/api/pictures/photos/47.jpg','gp':['/c18/api/pictures/gps/47/1.jpg','/c18/api/pictures/gps/47/2.jpg']},
{'name':'周一舟'  , 'num':48,'photo':'/c18/api/pictures/photos/48.jpg','gp':['/c18/api/pictures/gps/48/1.jpg','/c18/api/pictures/gps/48/2.jpg']},
{'name':'兰周'    , 'num':49,'photo':'/c18/api/pictures/photos/49.jpg','gp':['/c18/api/pictures/gps/49/1.jpg','/c18/api/pictures/gps/49/2.jpg']},
{'name':'欧阳胤阁', 'num':50,'photo':'/c18/api/pictures/photos/50.jpg','gp':['/c18/api/pictures/gps/50/1.jpg','/c18/api/pictures/gps/50/2.jpg']}
]
for i in datas:
    c18db.roster.update_one({'num':i['num']},{'$set':i})